#!/bin/bash -e

echo 'bitkey' | sudo tee /etc/hostname


# update gsettings with customizations
glib-compile-schemas /usr/share/glib-2.0/schemas

# update db for overlayed desktop files
update-desktop-database

# set ownership on user's home
chown -R user:user /home/user

#set user as cups admin
sudo usermod -aG lpadmin user

# configure nodm
NODM_CONF="/etc/default/nodm"
sed -i 's|NODM_USER=.*|NODM_USER=user|' $NODM_CONF
sed -i 's|NODM_XSESSION=.*|NODM_XSESSION="/home/user/.xsession"|' $NODM_CONF
chmod +x /home/user/.xsession

# set ownership of automounted usb devices
#CONF=/etc/usbmount/usbmount.conf
#MOUNTOPTIONS="uid=user,gid=user,sync,noexec,nodev,noatime,nodiratime"
#sed -i "s|^MOUNTOPTIONS=.*|MOUNTOPTIONS=\"$MOUNTOPTIONS\"|" $CONF

